# fly.toml app configuration file generated for subspace-frontend on 2023-07-05T12:15:01-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "subspace-frontend"
primary_region = "iad"

[env]
  BASE_URL = "https://subspace-backend.fly.dev"
  PORT = "80"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
