// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnLLLK1J12be2ifxvNyB4rie3wsJ6x0dE',
    appId: '1:914191054663:web:62d6169c0dd07122db3e62',
    messagingSenderId: '914191054663',
    projectId: 'subspace-1de63',
    authDomain: 'subspace-1de63.firebaseapp.com',
    storageBucket: 'subspace-1de63.appspot.com',
    measurementId: 'G-PDZ832QVSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_Rw_nUzcj8yXW6tQYpEqqMv-yBBMgZE',
    appId: '1:914191054663:android:cfb6da3d337a1774db3e62',
    messagingSenderId: '914191054663',
    projectId: 'subspace-1de63',
    storageBucket: 'subspace-1de63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4x4nYWdPFqAhmo38zkQObw7LO_nD-CEs',
    appId: '1:914191054663:ios:7da3437bd2c3743bdb3e62',
    messagingSenderId: '914191054663',
    projectId: 'subspace-1de63',
    storageBucket: 'subspace-1de63.appspot.com',
    iosClientId: '914191054663-thpmtbf3uu8mo99b78r4jn7bbcn33pme.apps.googleusercontent.com',
    iosBundleId: 'subspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4x4nYWdPFqAhmo38zkQObw7LO_nD-CEs',
    appId: '1:914191054663:ios:7206a07c09e42ebddb3e62',
    messagingSenderId: '914191054663',
    projectId: 'subspace-1de63',
    storageBucket: 'subspace-1de63.appspot.com',
    iosClientId: '914191054663-ef950sl9jh7su6ejsiehe0oog0kcflcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
